{
  "uid" : "dfb84cfd6bd259c5",
  "name" : "POST Create user as {0}",
  "fullName" : "tests.create_users_test.TestCreateUser#test_post_create_user_as_none",
  "historyId" : "cd94d860dfdeb87333e86cd60e9164d3",
  "time" : {
    "start" : 1708388624002,
    "stop" : 1708388624232,
    "duration" : 230
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL Bag\n\nAssertionError: Unexpected status code. Expected not 201. Actual: 201",
  "statusTrace" : "self = <tests.create_users_test.TestCreateUser object at 0x7ff94271d550>\n\n    @pytest.mark.xfail(reason='Bag')\n    @allure.title('POST Create user as {}')\n    def test_post_create_user_as_none(self):\n        response = BaseRequests.post(url='api/users', headers={})\n>       Assertions.assert_is_not_code_status(response, self.status.STATUS_CODE_201)\n\ntests/create_users_test.py:81: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [201]>, expected_status_code = 201\n\n    @staticmethod\n    def assert_is_not_code_status(response: Response, expected_status_code):\n        \"\"\"Check status code is wrong\"\"\"\n        actual_status_code = response.status_code\n        with allure.step(f'Expected status is not equal {expected_status_code}'):\n>           assert actual_status_code != expected_status_code, \\\n                f'Unexpected status code. Expected not {expected_status_code}. Actual: {actual_status_code}'\nE           AssertionError: Unexpected status code. Expected not 201. Actual: 201\n\nbase/assertions.py:27: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1708388620677,
      "stop" : 1708388620692,
      "duration" : 15
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : false,
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "testStage" : {
    "status" : "skipped",
    "statusMessage" : "XFAIL Bag\n\nAssertionError: Unexpected status code. Expected not 201. Actual: 201",
    "statusTrace" : "self = <tests.create_users_test.TestCreateUser object at 0x7ff94271d550>\n\n    @pytest.mark.xfail(reason='Bag')\n    @allure.title('POST Create user as {}')\n    def test_post_create_user_as_none(self):\n        response = BaseRequests.post(url='api/users', headers={})\n>       Assertions.assert_is_not_code_status(response, self.status.STATUS_CODE_201)\n\ntests/create_users_test.py:81: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [201]>, expected_status_code = 201\n\n    @staticmethod\n    def assert_is_not_code_status(response: Response, expected_status_code):\n        \"\"\"Check status code is wrong\"\"\"\n        actual_status_code = response.status_code\n        with allure.step(f'Expected status is not equal {expected_status_code}'):\n>           assert actual_status_code != expected_status_code, \\\n                f'Unexpected status code. Expected not {expected_status_code}. Actual: {actual_status_code}'\nE           AssertionError: Unexpected status code. Expected not 201. Actual: 201\n\nbase/assertions.py:27: AssertionError",
    "steps" : [ {
      "name" : "Expected status is not equal 201",
      "time" : {
        "start" : 1708388624232,
        "stop" : 1708388624232,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: Unexpected status code. Expected not 201. Actual: 201\n",
      "statusTrace" : "  File \"/home/runner/work/reqres/reqres/base/assertions.py\", line 27, in assert_is_not_code_status\n    assert actual_status_code != expected_status_code, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "hasContent" : true,
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "hasContent" : true,
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Create User"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reason='Bag')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "create_users_test"
  }, {
    "name" : "subSuite",
    "value" : "TestCreateUser"
  }, {
    "name" : "host",
    "value" : "fv-az1024-431"
  }, {
    "name" : "thread",
    "value" : "2231-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.create_users_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 2,
        "passed" : 0,
        "unknown" : 0,
        "total" : 2
      },
      "items" : [ {
        "uid" : "496bebc1814ec46e",
        "reportUrl" : "https://Nat754.github.io/reqres/4//#testresult/496bebc1814ec46e",
        "status" : "skipped",
        "statusDetails" : "XFAIL Bag\n\nAssertionError: Unexpected status code. Expected not 201. Actual: 201",
        "time" : {
          "start" : 1708385919649,
          "stop" : 1708385920009,
          "duration" : 360
        }
      } ]
    },
    "tags" : [ "@pytest.mark.xfail(reason='Bag')" ]
  },
  "source" : "dfb84cfd6bd259c5.json",
  "parameterValues" : [ ]
}