{
  "uid" : "e601367bc33908c2",
  "name" : "2.8 POST Create user get to http",
  "fullName" : "tests.create_users_test.TestCreateUser#test_create_users_to_http",
  "historyId" : "07f87128a6eeb419bf537f16f4512fc8",
  "time" : {
    "start" : 1708420748261,
    "stop" : 1708420748355,
    "duration" : 94
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL Bag\n\nAssertionError: Unexpected status code. Expected not 200. Actual: 200",
  "statusTrace" : "self = <tests.create_users_test.TestCreateUser object at 0x7fdf042fc650>\n\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason='Bag')\n    @allure.title(\"2.8 POST Create user get to http\")\n    def test_create_users_to_http(self):\n        response = requests.post(url=f'{self.constant.WRONG_URL}api/users', headers=self.data.CREATE_USER)\n>       Assertions.assert_is_not_code_status(response, self.status.STATUS_CODE_200)\n\ntests/create_users_test.py:104: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>, expected_status_code = 200\n\n    @staticmethod\n    def assert_is_not_code_status(response: Response, expected_status_code):\n        \"\"\"Check status code is wrong\"\"\"\n        actual_status_code = response.status_code\n        with allure.step(f'Expected status is not equal {expected_status_code}'):\n>           assert actual_status_code != expected_status_code, \\\n                f'Unexpected status code. Expected not {expected_status_code}. Actual: {actual_status_code}'\nE           AssertionError: Unexpected status code. Expected not 200. Actual: 200\n\nbase/assertions.py:27: AssertionError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1708420744987,
      "stop" : 1708420745002,
      "duration" : 15
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "skipped",
    "statusMessage" : "XFAIL Bag\n\nAssertionError: Unexpected status code. Expected not 200. Actual: 200",
    "statusTrace" : "self = <tests.create_users_test.TestCreateUser object at 0x7fdf042fc650>\n\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason='Bag')\n    @allure.title(\"2.8 POST Create user get to http\")\n    def test_create_users_to_http(self):\n        response = requests.post(url=f'{self.constant.WRONG_URL}api/users', headers=self.data.CREATE_USER)\n>       Assertions.assert_is_not_code_status(response, self.status.STATUS_CODE_200)\n\ntests/create_users_test.py:104: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nresponse = <Response [200]>, expected_status_code = 200\n\n    @staticmethod\n    def assert_is_not_code_status(response: Response, expected_status_code):\n        \"\"\"Check status code is wrong\"\"\"\n        actual_status_code = response.status_code\n        with allure.step(f'Expected status is not equal {expected_status_code}'):\n>           assert actual_status_code != expected_status_code, \\\n                f'Unexpected status code. Expected not {expected_status_code}. Actual: {actual_status_code}'\nE           AssertionError: Unexpected status code. Expected not 200. Actual: 200\n\nbase/assertions.py:27: AssertionError",
    "steps" : [ {
      "name" : "Expected status is not equal 200",
      "time" : {
        "start" : 1708420748355,
        "stop" : 1708420748355,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: Unexpected status code. Expected not 200. Actual: 200\n",
      "statusTrace" : "  File \"/home/runner/work/reqres/reqres/base/assertions.py\", line 27, in assert_is_not_code_status\n    assert actual_status_code != expected_status_code, \\\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "epic",
    "value" : "Create User"
  }, {
    "name" : "tag",
    "value" : "@pytest.mark.xfail(reason='Bag')"
  }, {
    "name" : "tag",
    "value" : "negative"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "create_users_test"
  }, {
    "name" : "subSuite",
    "value" : "TestCreateUser"
  }, {
    "name" : "host",
    "value" : "fv-az1249-567"
  }, {
    "name" : "thread",
    "value" : "2230-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.create_users_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 4,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "1f8bf8dfde0bfa90",
        "reportUrl" : "https://Nat754.github.io/reqres/7//#testresult/1f8bf8dfde0bfa90",
        "status" : "skipped",
        "statusDetails" : "XFAIL Bag\n\nAssertionError: Unexpected status code. Expected not 200. Actual: 200",
        "time" : {
          "start" : 1708418354909,
          "stop" : 1708418355005,
          "duration" : 96
        }
      }, {
        "uid" : "8c71822cb360f8c2",
        "reportUrl" : "https://Nat754.github.io/reqres/6//#testresult/8c71822cb360f8c2",
        "status" : "skipped",
        "statusDetails" : "XFAIL Bag\n\nAssertionError: Unexpected status code. Expected not 200. Actual: 200",
        "time" : {
          "start" : 1708412186983,
          "stop" : 1708412187048,
          "duration" : 65
        }
      }, {
        "uid" : "ae006c1e2fbb5a9",
        "reportUrl" : "https://Nat754.github.io/reqres/5//#testresult/ae006c1e2fbb5a9",
        "status" : "skipped",
        "statusDetails" : "XFAIL Bag\n\nAssertionError: Unexpected status code. Expected not 200. Actual: 200",
        "time" : {
          "start" : 1708388624242,
          "stop" : 1708388624307,
          "duration" : 65
        }
      } ]
    },
    "tags" : [ "negative", "@pytest.mark.xfail(reason='Bag')" ]
  },
  "source" : "e601367bc33908c2.json",
  "parameterValues" : [ ]
}